### PR TITLE
Fix #576.  Backported to 1.4.X series.

### LINKED ISSUE #576: Add client_secret to list of Rails filterered_paramters
sensitive information should be excluded from production logs.

see http://guides.rubyonrails.org/configuring.html

### PR DESCRIPTION
**Pull request by apsoto**
let me know if this is all the changes you need to help with cutting a release.  I wasn't sure if you needed the version.rb changed or if your release process handles that.

### CODE REVIEW

**Comment by tute** [comment]
Merged in https://github.com/doorkeeper-gem/doorkeeper/commit/457d9d4ce084b511594448ff25f6a2b84f9a7b8a, about to release 1.4.2. Thank you!

**Comment by elskwid** [comment]
I could hug you right now @apsoto! Thanks for back porting this change.

**Comment by tute** [comment]
I'll get a share of this hug too. :)

**Comment by elskwid** [comment]
HUGS FOR ALL!

I have PR open to update the advisory-db with version 1.4.2. 

https://github.com/rubysec/ruby-advisory-db/pull/131

Thanks again.

**Comment by tute** [comment]
Hugs for all indeed! Thank you very much @elskwid.

**Comment by apsoto** [comment]
Thanks for the advisory patch

**Pull request closed without merging**
