### PR TITLE
844 Allow rendering custom errors

### PR DESCRIPTION
**Pull request by maciekkolodziej**
Allow rendering custom errors

Set handle_auth_errors = :raise in initializer to raise exceptions insteads rendering response on unauthorized requests.

https://github.com/doorkeeper-gem/doorkeeper/issues/844

### CODE REVIEW

**Comment by maciekkolodziej** [comment]
@maclover7  coverage decreased because initializer template is not tested at all. Besides that, it seems ok. Do you need any more info / work to perform review?

**Comment by nbulaj** [comment]
Hi @maciekkolodziej . Could you please update your branch to current master, add a changelog entry to NEWS.md file and squash commits to a single one?

**Comment by nbulaj** [comment]
Ping @maciekkolodziej

**Comment by nbulaj** [comment]
Forked and implemented, will be released with 5.x release

**Pull request closed without merging**
