### PR TITLE
Compare redirect_uri and grant uri without query

### PR DESCRIPTION
**Pull request by dmitrytrager**
when doing checks from authorization code request

Related to: https://github.com/doorkeeper-gem/doorkeeper/issues/949

### CODE REVIEW

**Comment by maclover7** [comment]
@dmitrytrager Can you add some tests for the new behavior, so we can see what it looks like?

**Comment by dmitrytrager** [comment]
@maclover7 ok, sure

**Comment by dmitrytrager** [comment]
@maclover7 done

**Comment by nbulaj** [comment]
@dmitrytrager can you update NEWS.md adding pull request ID for this feature description as it is done for all the others changes? And squash all the commits for @maclover7 please? Thanks!

**Comment by dmitrytrager** [comment]
Sure, will do.

**Comment by dmitrytrager** [comment]
@maclover7 @nbulaj closing this one with respect to https://github.com/doorkeeper-gem/doorkeeper/pull/974

**Pull request closed without merging**
