### PR TITLE
Fix random spec failures

### PR DESCRIPTION
**Pull request by donbobka**
Fix random spec failures because of random order.

For example current master will fail with seed 3152
```bash
bundle exec rspec --seed 3152

[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's 'rails' settings.
====> Doorkeeper ORM: 'active_record'
====> Doorkeeper version: 5.1.0.rc1
====> Rails version: 5.2.2
====> Ruby version: 2.5.1 on x86_64-darwin17

Randomized with seed 3152
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F...............F.......................................................................................................................................................................................................................*..........................................................................................................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Doorkeeper::TokensController when authorization has succeeded returns the authorization
     # verify need of these specs
     # ./spec/controllers/tokens_controller_spec.rb:7


Failures:

  1) Custom controller for routes GET /inner_space/scope/applications routes to applications controller
     Failure/Error: expect(get('/inner_space/scope/applications')).to route_to('custom_authorizations#index')
       No route matches "/inner_space/scope/applications"
     # ./spec/routing/custom_controller_routes_spec.rb:73:in `block (2 levels) in <top (required)>'

  2) Custom controller for routes GET /space/oauth/applications routes to applications controller
     Failure/Error: expect(get('/space/oauth/applications')).to route_to('custom_authorizations#index')
       No route matches "/space/oauth/applications"
     # ./spec/routing/custom_controller_routes_spec.rb:105:in `block (2 levels) in <top (required)>'

Finished in 6.58 seconds (files took 5.21 seconds to load)
883 examples, 2 failures, 1 pending

Failed examples:

rspec ./spec/routing/custom_controller_routes_spec.rb:72 # Custom controller for routes GET /inner_space/scope/applications routes to applications controller
rspec ./spec/routing/custom_controller_routes_spec.rb:104 # Custom controller for routes GET /space/oauth/applications routes to applications controller

Randomized with seed 3152
```

### CODE REVIEW

**Comment by nbulaj** [comment]
Hi @donbobka . Well, why it not work's with `before :all` hook? I thought rspec runs examples of one spec in random order, not the entire test suite. So why some example fails ?

**Comment by nbulaj** [comment]
Hmm, `POST /inner_space/scope/token` exists, while `GET /inner_space/scope/applications` not :hear_no_evil: 

image

**Comment by donbobka** [comment]
Checked a little bit deeper, found that's `Doorkeeper.configuration.api_only = true` leaking from somewhere. That's the reason why we have no applications routes.

**Comment by donbobka** [comment]
Probably the following code is leaking with `api_only = true`
https://github.com/doorkeeper-gem/doorkeeper/blob/a729e80248031c1030c4dc0f89474932fe0d6603/spec/lib/config_spec.rb#L548-L555

So, I fixed it with Doorkepper.configure block in before hook, but not sure that it's the best way.

**Comment by nbulaj** [comment]
Thanks @donbobka . It possibly can create an issue. Thanks for investigation and your contribution! :handshake:

**Pull request merged**
