### PR TITLE
Add doorkeeper-sequel extension to README

### PR DESCRIPTION
**Pull request by nbulaj**
Add [doorkeeper-sequel extension](https://github.com/nbulaj/doorkeeper-sequel) to "Other ORMs" list.

### CODE REVIEW

**Comment by tute** [comment]
Thank you!

**Comment by tute** [comment]
Merged in.

**Comment by nbulaj** [comment]
@tute [are you sure?](https://github.com/doorkeeper-gem/doorkeeper/blob/master/README.md) :)

**Comment by tute** [comment]
Yeah, it's weird. If you clone the repo, it includes:

```
commit 08e43933d49f2f2ffb46d1375d6e248ad57722c0
Author: Nikita Bulaj <nbulaj@users.noreply.github.com>
Date:   Wed Jul 6 17:30:32 2016 +0300

    Update README [ci skip] (#861)

    Add doorkeeper-sequel extension to "Other ORMs" list.
```

**Comment by tute** [comment]
Look at that author. Something didn't go well with the merge button.

**Comment by tute** [comment]
https://twitter.com/tutec/status/750786493275336704

**Comment by nbulaj** [comment]
Definitely something went wrong

Closed PR list:

screenshot_1
---

PR conversation:
screenshot_2

**Comment by tute** [comment]
Force pushed the commit. Thanks!

**Pull request closed without merging**
