### PR TITLE
Clarify how to add local redirect URIs

### PR DESCRIPTION
**Pull request by jfly**
One of our users was confused by the wording of this message and suggested this alternative wording, which I agree is superior.

### CODE REVIEW

**Comment by nbulaj** [comment]
Hi @jfly . What confusing you find in phrase "local tests"? I think it is clearly explain the purpose of native redirect uris. What do you rhink?

**Comment by jfly** [comment]
CC-ing @luis-j-ianez, who originally told me he found the message confusing. He can probably give more insight into this than I can.

If I were going to guess, I think the word "tests" is confusing because it makes a programmer think of test scripts, not development on localhost.

**Comment by Luis-J-Ianez** [comment]
Well, it's difficult to reproduce what my mind thought first when I read "Use blablabla for local tests". As now I understand the process, I can't reproduce the mistake, so to speak. But I remember that at first I thought the "blablabla" was a kind of alias for "localhost". In my view the new wording is more helpful.

**Comment by nbulaj** [comment]
So @jfly @Luis-J-Ianez maybe we can extend this message by adding something like "for development purposes" in order to improve understanding of the help message? What do you think?

Also can you please add a changelog entry to NEWS.md with descriptive comment of the changes and rebase to quash commits? Thanks for yo patience and work!

**Comment by jfly** [comment]
Done and done!

**Comment by nbulaj** [comment]
Great, thanks @jfly!

**Comment by jonatanklosko** [comment]
Hey, this message seems no longer accurate. As far as I can see, this behaviour relayed on a bug fixed in #976, namely: if you added `urn:ietf:wg:oauth:2.0:oob` in the first line of `redirect_uri`, followed by other URLs (e.g. localhost ones) they were not validated and thus worked like a charm. #976 makes all URLs validated, so adding `urn:ietf:wg:oauth:2.0:oob` has no effect on the other URLs.

**Pull request merged**
