### PR TITLE
Implemented PKCE

### PR DESCRIPTION
**Pull request by rsharrott**
https://github.com/doorkeeper-gem/doorkeeper/issues/975

### CODE REVIEW

**Comment by rsharrott** [comment]
Originally based on https://github.com/doorkeeper-gem/doorkeeper/pull/979

**Comment by nbulaj** [comment]
Hi @rsharrott . Looks good to me. But I agree with @moneytree-doug comments, that he placed for #979:

> - i18n message: The code challenge method must be "plain" or "S256" (quotes)
> - I don't think it should ever fallback. I would suggest removing || 'plain' entirely. The request should be extremely explicit especially if it's plain, since this method is strongly advised against the the RFC.

Moreover, can you please add a changelog entry to NEWS.md and rebase commits to squash them? Thanks.

**Comment by nbulaj** [comment]
Hi @rsharrott . Any changes here?

**Comment by bpieck** [comment]
So there is an issue here, too.
Specs say, you never should have code_challange in the redirect_uri - but this has. You test here, that it has code_challenge_method (I'd prefer even that not to be part of the redirected_to). I added

```
url_should_not_have_param('code_challenge')
```

To the test ```#withPKCE resource owner authorizes the client with code_challenge parameter set```
And it failed. So at this point it fails the https://tools.ietf.org/html/rfc7636 which sais:

```
4.4.  Server Returns the Code

   When the server issues the authorization code in the authorization
   response, it MUST associate the "code_challenge" and
   "code_challenge_method" values with the authorization code so it can
   be verified later.

   Typically, the "code_challenge" and "code_challenge_method" values
   are stored in encrypted form in the "code" itself but could
   alternatively be stored on the server associated with the code.  The
   server MUST NOT include the "code_challenge" value in client requests
   in a form that other entities can extract.

   The exact method that the server uses to associate the
   "code_challenge" with the issued "code" is out of scope for this
   specification.
```

I will add a PR to the moneytree:master then, to fix this.

**Comment by nbulaj** [comment]
Hey @bpieck, try to cooperate with @rsharrott in order to fix the issue.

**Comment by bpieck** [comment]
I already did the fix and will open a PR to moneytree repo. Maybe @rsharrot accepts it.

**Comment by bpieck** [comment]
Ok, my other issues are just gone away, with this implementation. So the small issue I mentioned seems for me really the only one (https://github.com/moneytree/doorkeeper/pull/20/commits/dce94e7849969e118df449072b3cd0d68db40ac9).

From me a :+1: (although I have nothing to say, of course :P )

Hope it gets merged into doorkeeper. If there is anything I can do, to help it to be possibly merged - please tell me. I'd like to be of assistance.

**Comment by nbulaj** [comment]
Looks like @rsharrott lost his interest to this PR (or just disappeared), so you can for the project and reimplement this PR (with some comments above and your issue fix), and then send a new PR.

I'm still waiting when @tute will publish an intermidiate Doorkeeper release to Rubygems (4.3), then I want to merge many this new features (including PKCE) to new major version, 5.0

**Comment by tute** [comment]
NIKIta, feel free to merge in PRs. When I’m available i can create a
release branch off of tag v4.3, which we can merge into master afterwards.
Thanks!

**Comment by bpieck** [comment]
ok

**Comment by nbulaj** [comment]
Hi @tute! I've made a release with a new version - [4.3.0](https://github.com/doorkeeper-gem/doorkeeper/releases/tag/v4.3.0). When you will be free, you can checkout it, build and publish to Rubygems. Thank you for your work! 

I will start to work on a new major release, there are a lot of work to do :)

**Comment by bpieck** [comment]
Opened a new PR, as requested.

**Comment by rsharrott** [comment]
Hey guys. I'm still interested, just didn't see the comments till today. I'm happy to work with the code where ever. Will close this in favor of https://github.com/doorkeeper-gem/doorkeeper/pull/1037

**Pull request closed without merging**
