### PR TITLE
Pass tests on Rails 6 and fix deprecated

### PR DESCRIPTION
**Pull request by jasl**
### Summary

- Refactor dummy app preventing Rails 6 crash
- Rails 6 needs rspec-rails 4 to pass some cases (relates to view, I think it because tenderlove give a big refactor on actionview)
- Fix deprecated `update_attributes` -> `update`, this no harm for older Rails
- Add Rails 6 to build matrix
- Pinned Rails 6 as default local development dependency

### Other Information

This is just a initial work, although it pass tests on Rails 6, Zeitwerk breaks old extending way, I have to fix it for my app. I already committed an issue #1211

Also, Doorkeeper's build matrix is huge, and since Devise and other popular gems starting remove support of Rails 4 and Ruby 2.1 - 2.3, I suggest Doorkeeper follow them, we can discuss at #1212

### CODE REVIEW

**Comment by jasl** [comment]
There still some `DEPRECATION Warning` caused by Rspec, ignored for now

**Comment by jasl** [comment]
I think this PR have 2 parts so I will not squash as Danger suggest for now

**Comment by jasl** [comment]
@nbulaj I think I've done this, you can review if you have time

**Comment by jasl** [comment]
squashed, waiting CI pass

**Comment by nbulaj** [comment]
Thanks @jasl ! Great work :+1:

**Pull request merged**
