### PR TITLE
Add Truffleruby head to CI

### PR DESCRIPTION
**Pull request by gogainda**

### CODE REVIEW

**Comment by nbulaj** [comment]
I don't actually sure that TruffleRuby already supports Rails and database adapters :thinking: 
Let's wait for the CI to finish, but I'm pretty sure if will fail :(

**Comment by gogainda** [comment]
In general Rails should be supported ( we have some rails application working already), but it greatly depends on additional gems, which may break on truffleruby

**Comment by gogainda** [comment]
installation is failing due to https://travis-ci.org/github/doorkeeper-gem/doorkeeper/jobs/755543002 issue, will get back to it later once blocking issue is dealt with

**Comment by gogainda** [comment]
@nbulaj btw, is there any plans on moving to Github Actions from Travis? Due to some recent changes on Travis side, truffleruby stopped working correctly and we currently dont know if it's going to be fixed any time soon

**Comment by nbulaj** [comment]
@gogainda it's a hard question. I have to check the limits of both projects to understand how easy and profitable it will be to move to GH actions. Btw I know puma users them, so maybe Doorkeer could also. Anyway need to spend some time for investigation

**Comment by gogainda** [comment]
@nbulaj btw, this is my local results:
```
====> Doorkeeper ORM: 'active_record'
====> Doorkeeper version: 5.5.0.rc2
====> Rails version: 6.1.1
====> Ruby version: 2.7.2 on x86_64-darwin19

Randomized with seed 26151
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 4 minutes 23.7 seconds (files took 35.17 seconds to load)
1121 examples, 0 failures

Randomized with seed 26151

[Coveralls] Outside the CI environment, not sending data.
nn@L35975MEU-2 doorkeeper % ruby -v                                                                                                             [8/02/21 | 12:34:20]
truffleruby 21.1.0-dev-ce592906, like ruby 2.7.2, GraalVM CE Native [x86_64-darwin]
nn@L35975MEU-2 doorkeeper %   
`

**Comment by nbulaj** [comment]
This is interesting @gogainda! Thanks for reporting, we have to add truffle to our CI

**Pull request closed without merging**
