### PR TITLE
Yield application to allow_grant_flow_for_client? client credentials …

### LINKED ISSUE #1398: `client` yielded to `allow_grant_flow_for_client` config can either be a client or an application object
### Steps to reproduce

When setting `allow_grant_flow_for_client` in the doorkeeper config, the `client` that is yielded can be of two different types.

* https://github.com/doorkeeper-gem/doorkeeper/blob/v.5.3.1/lib/doorkeeper/oauth/pre_authorization.rb#L36 yields the application.
* https://github.com/doorkeeper-gem/doorkeeper/blob/v.5.3.1/lib/doorkeeper/oauth/client_credentials/validator.rb#L29 yields the client.
* https://github.com/doorkeeper-gem/doorkeeper/blob/v.5.3.1/lib/doorkeeper/oauth/password_access_token_request.rb#L53 yields the client.

Is this intentional? It means when configuring the lamba, we must deal with the differing types.

This is using the latest released version 5.3.1. (links above to the code in 5.3.1)

Thanks

### PR DESCRIPTION
**Pull request by aclemons**
…validation

Closes #1398

### CODE REVIEW

**Comment by nbulaj** [comment]
Something wrong with the specs.

We had a case in the past when hooks could have Application instance or Doorkeeper::OAuth::Client, so maybe it makes sense to use this approach too

Maybe this one or somewhere else:

https://github.com/doorkeeper-gem/doorkeeper/blob/50efdb039110a6d8c2730896c619f31ded9942bc/lib/doorkeeper/oauth/authorization/token.rb#L11-L17

**Comment by nbulaj** [comment]
Ah, OK, I've checked ./spec/lib/oauth/client_credentials_integration_spec.rb:11 and seems like it's incorrect.

You could just use this one:

```ruby
let(:client) { Doorkeeper::OAuth::Client.new(FactoryBot.build_stubbed :application) }
```

And spec must pass

**Comment by aclemons** [comment]
Resolved the changelog merge conflict and updated the integration spec now.

**Comment by nbulaj** [comment]
Thanks @aclemons !

**Pull request merged**
