### PR TITLE
Handle random newlines in the grant_type param

### PR DESCRIPTION
**Pull request by andrewclink**
When x-www-form-encoded data is posted to /oauth/token, the possibility of an invisible newline at the end can suck away more development time than one might want to spend on a Saturday morning.

Tests still pass. 

I don't know if this is the right place to handle it, but in lieu of more descriptive error messages (at least in development), this obviates the problem.

### CODE REVIEW

**Comment by maclover7** [comment]
@andrewclink Thanks for the PR! Can you handle it [here](https://github.com/doorkeeper-gem/doorkeeper/blob/master/app/controllers/doorkeeper/tokens_controller.rb#L74), where we grab the param from the hash? Thanks!

**Comment by maclover7** [comment]
@andrewclink Can you squash down your commits, and add a test for the new behavior? Looks to ready to go after that.

**Comment by nbulaj** [comment]
@andrewclink what about squashing commits? And I think you need to add an entry to the `NEWS.md` (take a look at some previous items in the file for example).

**Comment by andrewclink** [comment]
Sorry for the delay; I'll see if I can get some time this afternoon to take care of it.

**Comment by nbulaj** [comment]
Hi @andrewclink. Any changes would come?

**Comment by nbulaj** [comment]
Hi @andrewclink. Any changes here?

**Comment by nbulaj** [comment]
What if newline will be not only in `grant_type` parameter (`code`, for example)?

**Comment by nbulaj** [comment]
Closing due to lack of activity. Feel free to send this PR once again with fixed comments

**Pull request closed without merging**
