### PR TITLE
Test on Ruby 2.4

### PR DESCRIPTION
**Pull request by connorshea**
Happy holidays!

### CODE REVIEW

**Comment by connorshea** [comment]
until https://github.com/rails/rails/commit/47c49242913abbcdb8f798f53324769892d18c97 is released in Rails 4.2.8, Ruby 2.4 won't work with it.

**Comment by tute** [comment]
> Maybe we shouldn't merge this until 4.2.8 is out?

I'd wait for it. Thanks! 🎉

**Comment by connorshea** [comment]
@maclover7 now that Rails 4.2.8 is out can we merge? :)

**Comment by maclover7** [comment]
:+1: Thank you for your contribution!

:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by connorshea** [comment]
@maclover7 thanks for helping maintain the gem! ❤️

**Pull request merged**
