### PR TITLE
Allow customising the Doorkeeper::ApplicationController base controller

### PR DESCRIPTION
**Pull request by jvenezia**
Related to https://github.com/doorkeeper-gem/doorkeeper/issues/465.

Usefull to keep Doorkeeper controllers in the same context than the rest of your app.

### CODE REVIEW

**Comment by jvenezia** [comment]
Actually we could do a devise-like solution. Devise has no `ApplicationController` of his own and inherits all controllers from the users `ApplicationController`, and you can choose another one with the `parent_controller` option. Then it injects helpers in the actual parent controller.

I think it's a nicer solution than what I actually done here.

What do you think ?

**Comment by jvenezia** [comment]
Hi, any thought on this?

**Comment by tute** [comment]
Thank you! 👏

**Comment by apanzerj** [comment]
Thank you as well! We were just hacking around with this. Would love a release!

**Comment by tute** [comment]
You got it: https://rubygems.org/gems/doorkeeper/versions/4.1.0

**Comment by apanzerj** [comment]
Thanks!

**Pull request merged**
