### PR TITLE
Add api_only option

### PR DESCRIPTION
**Pull request by treble37**
- Use doorkeeper without management views for API only Rails apps
- Addresses #879

### CODE REVIEW

**Comment by tute** [comment]
Exciting changes. Thank you! A few comments:

- This is a new feature as much as a bug fix, next version should be 4.3.0.
- Please add a space in the NEWS title: `## 4.3.0`
- Please add documentation in the README on how to use this option
- Can you please address Hound's comments on new code?

Thank you so much!

**Comment by treble37** [comment]
Thank you for the feedback, I updated with the changes requested!

**Comment by lcpriest** [comment]
Anything I can do to help this PR along?

**Comment by tute** [comment]
Hi! Thanks for your comment. I'd like someone with this issue in their app to verify this is the right approach (asked also in https://github.com/doorkeeper-gem/doorkeeper/issues/879#issuecomment-252651921). Can you do that? Thanks!

**Comment by nbulaj** [comment]
@tute looks good. If question is only in routes - then it is a good and simple solution.

**Comment by whatthewhat** [comment]
> I'd like someone with this issue in their app to verify this is the right approach (asked also in #879 (comment)). Can you do that? Thanks!

@tute Hi! We have been using doorkeeper with these options (which are identical to this PR from what I can tell) for a while now:

```ruby
use_doorkeeper do
  skip_controllers :applications, :authorized_applications
end
```

I think a more interesting problem for the `api_only` mode is actually the `authorizations` controller<sup>*</sup>, bit this is a good first step! 👍 


<sup>*</sup> at the moment we have a separate base controller that can render html to handle that, but it could be interesting to experiment with proxying these screens to a JS app..

**Comment by cickes** [comment]
How do you authorize an app under this feature?  Assuming API Only access, using a POST request to /oauth/authorize yields a CSRF error.  
````ruby
Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms)

ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)
````  

Normally this can be overriden via `protect_from_forgery with: :null_session`.  However, I am not having success.  Thoughts?

**Comment by nbulaj** [comment]
Authorization flow is something that is hard to implement for the API project. What to do with redirects? So there are some questions about using that grant flow in the API mode...

**Comment by cickes** [comment]
Need to create 2 services then?  
1) Public service (obviously protected) authorization service (via authorization flow)
2) API Only service for token creation / `doorkeeper_authorize!`

**Comment by leviathan** [comment]
I'm using `ruby=2.2.5` and `Rails=5.0.1`. 
My rails app is running in API only mode (`Rails::Application.config.api_only = true`).

I'm running this branch in my project:
```
gem 'doorkeeper', :git => 'https://github.com/treble37/doorkeeper', :branch => 'api-only-879'
```

And routing is configured as suggested:
```
Rails.application.routes.draw do
  use_doorkeeper api_only: true
  ...
```

The Rails docs suggest that the application controller should inherit from `ActionController::API`.
But when using: `class ApplicationController < ActionController::API`
then any request to the rails server fails with:

```
Uncaught exception: undefined method `layout' for Doorkeeper::ApplicationsController:Class
	/.rvm/gems/ruby-2.2.5/bundler/gems/doorkeeper-1cee208d2e6b/app/controllers/doorkeeper/applications_controller.rb:3:in `<class:ApplicationsController>'
	/.rvm/gems/ruby-2.2.5/bundler/gems/doorkeeper-1cee208d2e6b/app/controllers/doorkeeper/applications_controller.rb:2:in `<module:Doorkeeper>'
	/.rvm/gems/ruby-2.2.5/bundler/gems/doorkeeper-1cee208d2e6b/app/controllers/doorkeeper/applications_controller.rb:1:in `<top (required)>
```

**When** using the `ActionController::Base` controller, then it works.
But using `ActionController::Base` totally defeats the purpose of having a Rails api_only app!!
```
class ApplicationController < ActionController::Base # works, but totally defeats api_only
```

**Suggestion:** Layout should also be excluded when doorkeeper is running in api mode.

**Comment by maclover7** [comment]
@treble37 would you be able to address the issues that were pointed out above? thanks!

**Comment by treble37** [comment]
Hi @maclover7, just getting back to this after a while, let me read up on the comments and report back!

**Comment by anik3tra0** [comment]
any update?

**Comment by maclover7** [comment]
@anik3tra0 Currently waiting for @treble37 to update the PR, and for more people to test that this works with their app

**Comment by frodsan** [comment]
I had to add this to make it work with Rails-api:

```
# frozen_string_literal: true

class DoorkeeperController < ApplicationController
  def self.protect_from_forgery(*); end

  def self.layout(*); end
end
```

**Comment by ssilvius** [comment]
What is left to do here? @treble37, I'll take this PR off your hands if you could write up a quick todo list.

**Comment by treble37** [comment]
Thank you @ssilvius. I haven't had a chance to look at this and probably won't so thank you for being willing to help!   here's a quick todo list:

1) Rebase the branch against latest master
2) Address the above  comments https://github.com/doorkeeper-gem/doorkeeper/pull/893#issuecomment-274570199 and https://github.com/doorkeeper-gem/doorkeeper/pull/893#issuecomment-260742204
3) Test against the versions of Rails that need to be supported

Thanks again!

**Comment by andresperezl** [comment]
I'm proposing a simple change that addresses both problems in comments https://github.com/doorkeeper-gem/doorkeeper/pull/893#issuecomment-274570199 and https://github.com/doorkeeper-gem/doorkeeper/pull/893#issuecomment-260742204

Simply add to [`application_controller.rb`](https://github.com/doorkeeper-gem/doorkeeper/blob/master/app/controllers/doorkeeper/application_controller.rb):

```ruby
protect_from_forgery with: :exception unless ApplicationController <= ActionController::API
```

This then will involve a two steps process for the user, set the routes with the `user_doorkeeper api_only: true` option and changing the config of  `config.base_controller = 'ActionController::API`

But there is one problem that I'm seeing, and if that if we want to follow the suggestion on  to use `ActionController::API` we need to bump the minimum rails version to 5.0, which was the first release including this class, after merging into rails the  [`rails-api` gem](https://github.com/rails-api/rails-api).

The other option would be using the rails-api gem directly but when running rake, it outputs this errors 
```
Failure/Error: wrap_parameters format: [:json]

NoMethodError:
  undefined method `wrap_parameters' for ActionController::API:Class
```

When using Rails 5, rake runs cleanly.

Fork with proposed change and rebased: https://github.com/andresperezl/doorkeeper/commit/d9094a8b7383dca6a99fa601e6ac297f96cf5894

**Comment by JoeWoodward** [comment]
Another option would be to use `respond_to?(: protect_from_forgery)`

**Comment by nbulaj** [comment]
Hi @treble37. I prefer the solution proposed in #992. It also handles `protect_from_forgery`, Doorkeeper API option, routes and etc, but has more: helpers restriction, redirect cases, JSON responses for API requests, more specs. How to you think, can we continue our work in that direction?

**Comment by nbulaj** [comment]
Closing this PR in order to concentrate work on more solid #992

**Pull request closed without merging**
