### PR TITLE
Fix uri comparing

### PR DESCRIPTION
**Pull request by dmitrytrager**
when doing checks from authorization code request

Related to: https://github.com/doorkeeper-gem/doorkeeper/issues/949

### CODE REVIEW

**Comment by nbulaj** [comment]
@maclover7 I think it is ready to be merged.

**Comment by maclover7** [comment]
Hi @dmitrytrager! Can you squash your commits? Other than that, looks ready to go 👍

**Comment by dmitrytrager** [comment]
@maclover7 Tried to squach commit. Please, check.

**Comment by maclover7** [comment]
@dmitrytrager Looks like the squash worked, but your commit message got cleared somehow. Maybe try using `git commit --amend` to edit it? 😬

**Comment by dmitrytrager** [comment]
Hey @maclover7 

This is commit I'm able to see:
commit

If you think this is not appropriate message, please, add whatever you want to this message)

**Comment by maclover7** [comment]
@dmitrytrager Can you please rename the commit and its body to be more descriptive? Having `# This is a combination of 3 commits.` is not very informative about the changes being made 😞

**Comment by dmitrytrager** [comment]
okay

**Comment by dmitrytrager** [comment]
@maclover7 is it ok now?

**Comment by StupidCodeFactory** [comment]
We're getting 401's when using Doorkeeper with the omniauth gem to login which appends query params. 

@maclover7 any chance to get this in?

Thanks

**Comment by nbulaj** [comment]
Thanks @dmitrytrager!

**Pull request merged**
