### PR TITLE
Use attr_accessible only if object responds to attr_accessible

### PR DESCRIPTION
**Pull request by knovoselic**
Fixed problem described in #541.

### CODE REVIEW

**Comment by tute** [comment]
Now I remember why this solution doesn't work, see failure:

```
/home/travis/build/doorkeeper-gem/doorkeeper/vendor/bundle/ruby/2.0.0/gems/activemodel-4.0.13/lib/active_model/deprecated_mass_assignment_security.rb:14:in `attr_accessible': `attr_accessible` is extracted out of Rails into a gem. Please use new recommended protection model for params(strong_parameters) or add `protected_attributes` to your Gemfile to use old one. (RuntimeError)
```

https://travis-ci.org/doorkeeper-gem/doorkeeper/jobs/47352188

Thank you for your work anyway.

**Comment by knovoselic** [comment]
Hey @tute , I've pushed another commit which should fix this problem. Do I need to create another pull request or is this one going to get updated?
Can I somehow run tests using Travis on my forked repo?

**Comment by tute** [comment]
Travis running, sorry I closed it too early. :)

**Comment by tute** [comment]
This change though means that mongo ORMs won't have `attr_accessible`, as few people will see they need to add `include ActiveModel::MassAssignmentSecurity` to their models.

What I would love is not need parameters protection in the codebase, remove this lines, and anywhere we call `save` or the `update` flavors, inline each attribute to make sure this vulnerability doesn't exist.

That would be a refactor, I'm not sure if it would be wiser future-thinking anyways.

**Comment by knovoselic** [comment]
Yeah, they won't have `attr_access`, but they will still be protected with strong parameters. Maybe a note in readme or a warning is enough? 
Another solution would be to manually include `ActiveModel::MassAssignmentSecurity` if it's defined in doorkeeper mongoid models. What do you think about that?

The best solution would be refactor, but that could take a lot of time and effort.

**Comment by tute** [comment]
> Another solution would be to manually include `ActiveModel::MassAssignmentSecurity` if it's defined in mongo models. What do you think about that?

That's better.

**Pull request closed without merging**
